// Generated by LiveScript 1.2.0
(function(){
  module.exports = {
    port: 4000,
    url: 'http://localhost:4000',
    mongo: {
      db: 'answer-system',
      host: 'localhost',
      port: 27017,
      writeConcern: -1,
      collections: ['questions', 'users', 'courier']
    },
    baiduMapUrl: 'http://api.map.baidu.com/geocoder/v2',
    ak: '7E5AC0bfb3c61d2d80cb86986ec42dbf',
    hostEmail: '415619323@qq.com',
    hostPassword: 'ksda21064711'
  };
}).call(this);
